version: '3'

services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DB_HOST: postgres
    ports:
      - 3000:3000
    depends_on:
      - postgres

volumes:
  postgres-data:
